name: Raccoon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    - name: Deploy
      uses: FranklinPetra/Raccoon
      with: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER:  build/wwwroot  
          SINGLE_COMMIT: true
